### ISSUE TITLE
Problem importing Markdown

### ISSUE THREAD

**Issue by stefandjuric** [aguingand/tiptap-markdown#13]
**Describe the bug**
import { Markdown } from 'tiptap-markdown';
I had a problem importing Markdown. When I import Markdown like this, ts gives me this message `'Markdown' only refers to a type, but is being used as a value here`. When I opened your library I noticed that you export type `export type Markdown = Extension<MarkdownOptions, MarkdownStorage>;` from the index.d.ts file and not the object located in the src folder that I actually need. For now I put ```
// @ts-ignore
import { Markdown } from 'tiptap-markdown/src';
``` .

**To Reproduce**
Steps to reproduce the behavior:
You just need to import Markdown as explained in the documentation and then insert it as an extension. And TS will give you an error message.
```
 extensions: [
      Markdown,
      StarterKit
]
```

**Expected behavior**
You need to export Mardown from the src/Markdown.tsx file.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser: chrome

**Comment by aguingand** [comment]
Fixed in 0.7.1 (https://github.com/aguingand/tiptap-markdown/commit/a8e8236a651394a19ee96159f29e0b05c91967f4). You can update to the latest version.
