### ISSUE TITLE
Example with markdown directives

### ISSUE THREAD

**Issue by jlarmstrongiv** [aguingand/tiptap-markdown#15]
**Is your feature request related to a problem? Please describe.**

When authoring documentation, websites, and other mediums with markdown, it may be necessary to add additional syntax.  

The [generic directives/plugins syntax proposal](https://talk.commonmark.org/t/generic-directives-plugins-syntax/444) is:

>  a proposal for a generic syntax to accommodate custom directives/plugins, which is as simple and markdown-like as possible while still accommodating a lot of use cases. While not enabling all markdown extensions (e.g. tables, custom linebreak behaviour etc. doesn’t really fit the template), it works for a lot of them. 

Examples include:
- `:cite[smith04]`
- `::youtube[Video of a cat in a box]{v=01ab2cd3efg}`

**Describe the solution you'd like**

It would be great to have directive support built into `tiptap-markdown`, or an example demonstrating how to add something like `::youtube[Video of a cat in a box]{v=01ab2cd3efg}`

**Describe alternatives you've considered**

Skipping markdown and using tiptap extensions instead.  I really like the markdown syntax, authoring experience, readability, and shortcuts.  Markdown extensions cover so many use-cases, I feel like it would be the right solution / escape hatch for most custom syntax.  

**Additional context**

There are plugins to support this syntax:
- https://github.com/hilookas/markdown-it-directive
- https://github.com/remarkjs/remark-directive

**Comment by aguingand** [comment]
This package only handle standardized commonmark / GFM syntax by default but you can add custom parsing/serializing logic as described [here](https://github.com/aguingand/tiptap-markdown#custom-extensions). There is some examples of custom extensions [here](https://github.com/aguingand/tiptap-markdown/tree/main/example/src/extensions).

**Comment by aguingand** [comment]
Of course a PR is welcomed if you have a clean example of directive extension 👍
