### ISSUE TITLE
how to handle when user paste markdown

### ISSUE THREAD

**Issue by SteveSuv** [aguingand/tiptap-markdown#16]
for example: when user paste '# hello world \n\n- l1\n- l2'
the editor can't handle:
![image](https://github.com/aguingand/tiptap-markdown/assets/35391006/79e47102-b7e5-4fc3-ab7e-ece44de9ecf2)

what i hope to show:
![image](https://github.com/aguingand/tiptap-markdown/assets/35391006/5d00fcd5-9731-4a6c-837f-56ef579237da)

what should i do ?

**Comment by aguingand** [comment]
This feature is not currently available but I may add it in the future.

**Comment by aguingand** [comment]
Released in v0.8.0, [two options](https://github.com/aguingand/tiptap-markdown#options) where added (`transformPastedText` & `transformCopiedText`)
