### ISSUE TITLE
Some Markdown Elements Don't Fomat

### ISSUE THREAD

**Issue by codeser** [aguingand/tiptap-markdown#23]
**Describe the bug**
Some markdowns don't format
eg. 
Headings, lists etc.
Please see image below of markdown output:
![Screen Shot 2023-06-23 at 12 29 00 PM](https://github.com/aguingand/tiptap-markdown/assets/44587599/6eeb1f30-c255-4340-94df-042744e9c477)

Love your library and look forward to your response :)

**Comment by aguingand** [comment]
Can you provide a reproduction of your issue ?

**Comment by codeser** [comment]
Oops my bad, I figured out the problem was because react was manipulating the html 

For anyone that faces similar issues, the problem is to wrap the markdown with:

`   <div className="prose lg:prose-xl"> {markdown_goes_here} </div>
