### ISSUE TITLE
Tables are not rendered

### ISSUE THREAD

**Issue by codeser** [aguingand/tiptap-markdown#27]
**Describe the bug**

Valid markdown syntax for tables is rendered as raw strings instead of rendering the correct table format.

**To Reproduce**
1. Create Markdown string including table syntax
2. Render that markdown with the tiptap editor using tiptap-markdown extension
3. Check the rendered output and note the raw table

You can also see demo of bug on Codesandbox:
https://codesandbox.io/s/strange-bose-zzh5hh?file=/src/App.js

**Expected behavior**
Table rendered correctly according to markdown syntax.

**Screenshots**
![Screen Shot 2023-06-26 at 10 53 27 AM](https://github.com/aguingand/tiptap-markdown/assets/44587599/1de3762a-83ac-402a-a4ac-7379c4a2b1f1)

**Desktop (please complete the following information):**
 - Mac OSX
 - Chrome 114.0.5735.133

**Additional context**
Please see Codesandbox for demo of bug:
https://codesandbox.io/s/strange-bose-zzh5hh?file=/src/App.js

**Comment by aguingand** [comment]
You must include the tables extension to insert it (https://tiptap.dev/api/nodes/table)
