### ISSUE TITLE
Added spaces

### ISSUE THREAD

**Issue by Schroedi** [aguingand/tiptap-markdown#28]
**Describe the bug**
When pasting two lines without spaces into an editor with `breaks: true, transformPastedText: true`, there is a space at the start of the second line.

**To Reproduce**
1. Create an editor with the Markdown extension:
```ts
Markdown.configure({
  html: true,                  // Allow HTML input/output
  tightLists: true,            // No <p> inside <li> in markdown output
  tightListClass: 'tight',     // Add class to <ul> allowing you to remove <p> margins when tight
  bulletListMarker: '-',       // <li> prefix in markdown output
  linkify: false,              // Create links from "https://..." text
  breaks: true,               // New lines (\n) in markdown input are converted to <br>
  transformPastedText: true,  // Allow to paste markdown text in the editor
  transformCopiedText: true,  // Copied text is transformed to markdown
}),
```

2. Paste two lines from an text editor such as sublime text:
```
line1
line2
```

3. Observe that the editor displays:

```
line1
 line2
```

**Expected behavior**
The two lines without space in front of "line2".

**Screenshots**
![SCR-20230630-utn](https://github.com/aguingand/tiptap-markdown/assets/97124/d77fea72-8173-432d-8a5d-7415b170e544)

**Sample project**
[https://stackblitz.com/edit/vitejs-vite-tldxcq?file=src%2FApp.svelte](https://stackblitz.com/edit/vitejs-vite-tldxcq?file=src%2FApp.svelte)

**Comment by aguingand** [comment]
That may be because `markdown-it` adds an extra `\n` after the `<br>` which does not plays well with `preserveWhitespace` option.

**Comment by aguingand** [comment]
Fixed in v0.8.3

**Comment by aguingand** [comment]
@AlexRoidl Empty paragraphs does not exist in markdown, you can insert 2 hard breaks if you want an empty line. "breaks" option only convert single `\n` to `<br>` which is the default github behavior.

**Comment by iksent** [comment]
@aguingand, please advice, how to convert empty paragraph to line break?

My case: User enters this text:

```
line1

line2
```

Then I send it to API, getting it again and user sees in the editor:

```
line1
line2
```

without empty line... :(

**Comment by hamonCordova** [comment]
@iksent I would love to know as well.

**Comment by AlexRoidl** [comment]
@iksent @hamonCordova @aguingand I am also still struggeling with this

**Comment by hamonCordova** [comment]
> [@iksent](https://github.com/iksent) [@hamonCordova](https://github.com/hamonCordova) [@aguingand](https://github.com/aguingand) I am also still struggeling with this

Since 2023 you seem to be struggling with that, that's crazy we don't have any fix or a response. 
By the way, did you find any workaround?

**Comment by iksent** [comment]
I came to the conclusion that markdown by its nature does not support empty lines (double hyphenation).

So I decided to add spaces between paragraphs like this:

```
.HtmlViewer {
  & > * {
    &:not(:last-child) {
      margin-bottom: 20px;
    }
  }
}
```

Also to make it display correctly, I replace `\n` to double `\n\n`:

```
<HtmlViewer content={md.render(content.replaceAll('\n', '\n\n')} />
```
