### ISSUE TITLE
More empty lines

### ISSUE THREAD

**Issue by stefandjuric** [aguingand/tiptap-markdown#30]
<img width="339" alt="Screenshot 2023-07-14 at 17 37 02" src="https://github.com/aguingand/tiptap-markdown/assets/16122856/83e4fc6d-d619-4363-b9a1-c4b8a4944e96">

If I have content in the editor like in the picture with more empty lines and I try to save it editor.storage.markdown.getMarkdown() it happens that the empty lines are skipped. And after I open the saved text again, I get content without empty lines (as in the picture below).

<img width="339" alt="Screenshot 2023-07-14 at 17 41 01" src="https://github.com/aguingand/tiptap-markdown/assets/16122856/fb8fa536-b161-41ad-888c-1e37fcba7de1">

**Comment by aguingand** [comment]
Empty paragraph doesn't exists in markdown but you can achieve this by inserting 2 [HardBreak](https://tiptap.dev/api/nodes/hard-break#keyboard-shortcuts)

**Comment by iksent** [comment]
I have exactly the same issue:

User enters this text:
```
1  
  
3
```

`getMarkdown` returns the same text with empty line.
I am setting this text again in editor, and users sees: 

```
1
3
```

without empty line :(
[HardBreak](https://tiptap.dev/api/nodes/hard-break#keyboard-shortcuts) extension didn't change the situation.
