### ISSUE TITLE
Guidance on customizing serialization for extensions

### ISSUE THREAD

**Issue by ctjlewis** [aguingand/tiptap-markdown#35]
See the [`@tiptap/extension-mention` example](https://tiptap.dev/api/nodes/mention) - how would we customize how these are serialized? All mentions serialize as `[mention]` (no name) by default.

See also: https://github.com/aguingand/tiptap-markdown/discussions/29

**Comment by ctjlewis** [comment]
### Solution

I was able to override this by customizing the `command` for the suggestion:

```ts
export const suggestion: Omit<SuggestionOptions, 'editor'> = {
  command: ({ editor, range, props: { id } }) => {
    editor.commands.insertContentAt(range, `@${id}`)
  },
  ...
}

**Comment by ctjlewis** [comment]
@aguingand - I reopened this because this basically disables the extension's ability to render anything but a text node, i.e. it cannot be styled.

**Comment by aguingand** [comment]
You should enable the `html` [option](https://github.com/aguingand/tiptap-markdown#options). It should render a `<span>` with appropriate attributes.

**Comment by ctjlewis** [comment]
With `{ html: false }`, the span is rendered correctly but is serialized as `[mention]`. With `{ html: true }`, it also renders correctly, but is now serialized as `<span data-type=&quot;mention&quot; class=&quot;mention&quot; data-id=&quot;Tom Cruise&quot;>@Tom Cruise</span>`.

**Comment by ctjlewis** [comment]
Oh, I see - this is by design, it *has* to serialize as `<span>...</span>` in Markdown in order to be able to parse it back to a Mention, and Markdown will render it anyway. Thanks so much for your help, apologies for this issue.
