### ISSUE TITLE
Do you have any plans to add YouTube video embedding? (feat. @tiptap/extension-youtube)

### ISSUE THREAD

**Issue by lainfox** [aguingand/tiptap-markdown#40]
Tiptap extensions [@tiptap/extension-youtube](https://www.npmjs.com/package/@tiptap/extension-youtube) is cool. But we can't use this extension due to serialize errors.

- Render html: ✅ 
```
<div data-youtube-video="">
<iframe width="640" height="480" allowfullscreen="true" autoplay="false" disablekbcontrols="false" enableiframeapi="false" endtime="0" ivloadpolicy="0" loop="false" modestbranding="false" origin="" playlist="" src="https://www.youtube.com/embed/jOTfBlKSQYY?si=QGfsxufMhjZHwjIa" start="0"></iframe>
</div>
```

- editor.storage.markdown.getMarkdown() : ⚠️  has HTML code
```
## Paragraph

<div data-youtube-video="">
<iframe width="640" height="480" allowfullscreen="true" autoplay="false" disablekbcontrols="false" enableiframeapi="false" endtime="0" ivloadpolicy="0" loop="false" modestbranding="false" origin="" playlist="" src="https://www.youtube.com/embed/jOTfBlKSQYY?si=QGfsxufMhjZHwjIa" start="0"></iframe>
</div>
...
```

- onCopy ❌ 
<img width="523" alt="image" src="https://github.com/aguingand/tiptap-markdown/assets/245237/a68ed5d5-6ec4-4ba2-8337-079c9371bfa6">

Hope to implement youtube extension 🙏

**Comment by aguingand** [comment]
This will always produce HTML because iframe has no equivalent in standard markdown.

This bug on copy is fixed in v0.8.3
