### ISSUE TITLE
Only first line of a multi-line table cell gets exported

### ISSUE THREAD

**Issue by ghoshsanjoy78** [aguingand/tiptap-markdown#41]
**Describe the bug**
Using the standard tiptap table extension, if a table cell has multiple lines in it, only the first line gets exported by the extension

**To Reproduce**
1. Create a table using tiptap table extension
2. Add some rows and columns
3. Insert some text with "new line" enter keys on multiple lines
4. Export to markdown using this extension
Exported markdown file only contains the first line

**Expected behavior**
All the lines in the table should be in the markdown export

**Screenshots**
![image](https://github.com/aguingand/tiptap-markdown/assets/40965395/d5e6e6e5-38b2-4e9d-8f23-18c851c5d05b)
![image](https://github.com/aguingand/tiptap-markdown/assets/40965395/17271124-91c7-4261-8a75-b7051c960d4b)

**Comment by aguingand** [comment]
Released in v0.8.3

**Comment by aguingand** [comment]
If multiple `<p>` are inserted, this will fallback to plain HTML table.
