### ISSUE TITLE
this repo has conflict with @tiptap/extension-code-block-lowlight

### ISSUE THREAD

**Issue by iowxy** [aguingand/tiptap-markdown#46]
**Describe the bug**
Empty break line and whitespaces are missing

**To Reproduce**
1. install packages
```bash
pnpm add @tiptap/extension-code-block-lowlight tiptap-markdown
```
2. insert code-block content like this:
```typescript
class A extends B<string> {

    public sayHello() {
       return 'hello';
    }
}
```
3. save content and re-render editor

**Expected behavior**
Expected:
```typescript
class A extends B<string> {

    public sayHello() {
       return 'hello';
    }
}
```
Actually:
```typescript
class A extends B<string> {
public sayHello() {
   return 'hello';
}
}
```

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser: chrome 
 - Version: 114

**Additional context**
This bug only happens when empty line exists.

I'm following official demo: https://tiptap.dev/examples/syntax-highlighting

**Comment by aguingand** [comment]
I can't reproduce, it sounds like `whitespace: pre-line` style is applied to your `pre` elements. If the spacing is definitely broken please provide me a full reproduction in Codesandbox or equivalent.

**Comment by iowxy** [comment]
@aguingand Plugin @tiptap/extension-code-block-lowlight will wrap `whitespace: pre-wrap` automatically for code-block.

Today I find out **the first** code-block is always works, and the others always showing unexpected format.

// First √
```typescript
class A extends B<string> {

    public sayHello() {
         return 'hello';
     }
}
```

// Second ×
```typescript
class A extends B<string> {
public sayHello() {
    return 'hello';
}
}
```

// Third ×
```typescript
class A extends B<string> {
public sayHello() {
    return 'hello';
}
}
```

**Comment by aguingand** [comment]
Can you provide a full reproduction of this issue (Codesandbox preferably or a repo)  ?

**Comment by iowxy** [comment]
Hi, I have created a simplest one repo: https://github.com/iowxy/markdown-conflict-reproduce , just run 
```bash
pnpm install && pnpm start
```

**Comment by iowxy** [comment]
One way code-block works
```html
<pre><code>....</code></pre>\n<pre><code>....</code></pre>
```

Another way doesn't work (missing `\n` between pre nodes)
```html
<pre><code>....</code></pre><pre><code>....</code></pre>
```

**Comment by aguingand** [comment]
Commonmark requires a `\n` between blocks if you use raw HTML, it's preferable to use <code>```</code> syntax. [See expected outputs](https://spec.commonmark.org/dingus/?text=**NOT%20OK**%0A%3Cpre%3E%3Ccode%3Eclass%20A%20%7B%0A%20%20%20%20public%20hello()%20%7B%0A%20%20%20%20%20%20%20%20console.log()%0A%20%20%20%20%7D%0A%7D%3C%2Fcode%3E%3C%2Fpre%3E%3Cpre%3E%3Ccode%3Eclass%20A%20%7B%0A%20%20%20%20public%20hello()%20%7B%0A%20%20%20%20%20%20%20%20console.log()%0A%20%20%20%20%7D%0A%7D%3C%2Fcode%3E%3C%2Fpre%3E%0A%0A**OK**%0A%3Cpre%3E%3Ccode%3Eclass%20A%20%7B%0A%20%20%20%20public%20hello()%20%7B%0A%20%20%20%20%20%20%20%20console.log()%0A%20%20%20%20%7D%0A%7D%3C%2Fcode%3E%3C%2Fpre%3E%0A%3Cpre%3E%3Ccode%3Eclass%20A%20%7B%0A%20%20%20%20public%20hello()%20%7B%0A%20%20%20%20%20%20%20%20console.log()%0A%20%20%20%20%7D%0A%7D%3C%2Fcode%3E%3C%2Fpre%3E%0A%0A**OK**%0A%60%60%60%0Aclass%20A%20%7B%0A%20%20%20%20public%20hello()%20%7B%0A%20%20%20%20%20%20%20%20console.log()%0A%20%20%20%20%7D%0A%7D%0A%60%60%60%0A%60%60%60%0Aclass%20A%20%7B%0A%20%20%20%20public%20hello()%20%7B%0A%20%20%20%20%20%20%20%20console.log()%0A%20%20%20%20%7D%0A%7D%0A%60%60%60)

**Comment by iowxy** [comment]
However  `editor.getHTML()` will not create **\n** for content
