### ISSUE TITLE
Odd behavior with hardBreaks and newlines

### ISSUE THREAD

**Issue by benank** [aguingand/tiptap-markdown#49]
**Describe the bug**
There are two parts to this bug report: `setContent` and `editor.storage.markdown.getMarkdown()`.

### Serialization Bug: `editor.storage.markdown.getMarkdown()`

When using this method, any single newlines (represented in JSONContent by two consecutive non-empty paragraph nodes) are converted into two newlines (a single hard break, or \n\n) when the markdown is serialized from the editor state. 

Editor content (two consecutive paragraph nodes):
```
line one
line two
```

Markdown output (actual):
```
line one

line two
```

Markdown output (expected):
```diff
line one
-                                 
line two
```

### Parsing Bugs: `setContent`

**Scenario 1:**

Scenario one is where the input has a single newline (\n), which should result in two paragraphs in the JSON output. However, a hardBreak is inserted.

```
editor.commands.setContent(markdownInput, true, {
    preserveWhitespace: true,
});
```

where `markdownInput` is:
```
line 1
line 2
```

<details>
  <summary>Output `editor.getJSON()` (actual)</summary>
  
  ```
 {
    "type": "doc",
    "content": [
        {
            "type": "paragraph",
            "content": [
                {
                    "type": "text",
                    "text": "line 1"
                },
                {
                    "type": "hardBreak"
                },
                {
                    "type": "text",
                    "text": "line 2"
                }
            ]
        }
    ]
}
  ```
  
</details>

<details>
  <summary>Output `editor.getJSON()` (expected)</summary>
  
  ```diff
 {
    "type": "doc",
    "content": [
        {
            "type": "paragraph",
            "content": [
                {
                    "type": "text",
                    "text": "line 1"
                },
-                {
-                    "type": "hardBreak"
-                },
                {
                    "type": "text",
                    "text": "line 2"
                }
            ]
        }
    ]
}
  ```
  
</details>

**Scenario 2:**

Scenario two is where the input has two or more newlines (\n\n), which should be preserved as a hardBreak in the JSON output. However, a hardBreak is not inserted.

```
editor.commands.setContent(markdownInput, true, {
    preserveWhitespace: true,
});
```

where `markdownInput` is:
```
line 1

line 2
```

<details>
  <summary>Output `editor.getJSON()` (actual)</summary>
  
  ```
 {
    "type": "doc",
    "content": [
        {
            "type": "paragraph",
            "content": [
                {
                    "type": "text",
                    "text": "line 1"
                }
            ]
        },
        {
            "type": "paragraph",
            "content": [
                {
                    "type": "text",
                    "text": "line 2"
                }
            ]
        }
    ]
}
  ```
  
</details>

<details>
  <summary>Output `editor.getJSON()` (expected)</summary>
  
  ```diff
 {
    "type": "doc",
    "content": [
        {
            "type": "paragraph",
            "content": [
                {
                    "type": "text",
                    "text": "line 1"
                },
+                {
+                   "type": "hardBreak"
+                },
                {
                    "type": "text",
                    "text": "line 2"
                }
            ]
        }
    ]
}
  ```
  
</details>

**To Reproduce**
1. See above steps with examples.

**Expected behavior**
See above.

**Desktop (please complete the following information):**
 - OS: Windows & MacOS
 - Browser: Chromium
 - Version 87
 - tiptap-markdown version: 0.8.4

**Additional context**
Please let me know if you need any additional clarification or if I am missing something here. Thanks!

**Comment by aguingand** [comment]
What is your configured option for the `Markdown` extension ?

The scenario 2 will always produce paragraphs, it's how markdown works.

For either cases, if you want to be sure when hard breaks appears, you should use the markdown syntax (`\\n` or `  \n`)

**Comment by benank** [comment]
Thanks for your response. My configuration for the `Markdown` extension is this:
```
  Markdown.configure({
    html: false,
    linkify: true,
    breaks: true,
  }),
  ```
  
> The scenario 2 will always produce paragraphs, it's how markdown works.

Ah I see. So a single newline will produce one paragraph element with a <br> between the text. Multiple newlines will produce multiple paragraphs without anything between them. Thank you, that helped solve scenario 1 and 2 for me.

I also learned that the reason my serialization doesn't work was because I was always splitting the current block when shift+enter is pressed instead of inserting a hardbreak for single new lines. All these issues are fixed now, thanks!
