### ISSUE TITLE
question: is this a tiptap extension, or a wrapper for the tiptap editor?

### ISSUE THREAD

**Issue by binyamin** [aguingand/tiptap-markdown#5]
1. Is this project a standalone editor component which _uses_ tiptap? Or, does it bundle the marks and nodes which are necessary to make tiptap compatible with markdown?
2. Also, which markdown feature-set is this based on? Ie. CommonMark, GFM, etc.

The story is, I have a bunch of blog posts written in markdown. I want to use tiptap, but I want to be sure it will work with my existing files without checking each post manually.

**Comment by aguingand** [comment]
1. it's an wrapper around tiptap `Editor` (so with the same API / extensions). It does not bundle tiptap Nodes/Marks (for size reasons) but defines how to parse / serialize them.
2. GFM
