### ISSUE TITLE
Tables support

### ISSUE THREAD

**Issue by Lenur29** [aguingand/tiptap-markdown#59]
Hi @aguingand,
Thank you for this extension. I would like to ask whether it is possible to display tables?

**Comment by aguingand** [comment]
Yes, follow the tiptap guide https://tiptap.dev/docs/editor/api/nodes/table, table are converted to markdown with this extension

**Comment by Lenur29** [comment]
@aguingand, thank you very much

**Comment by Lenur29** [comment]
@aguingand, Sorry for bothering you. Is it possible to handle the case when the table markdown comes from backend and I need to render it and edit(if necessary)?
