### ISSUE TITLE
Empty paragraphs / break dont get translated to markdown

### ISSUE THREAD

**Issue by lennardv2** [aguingand/tiptap-markdown#8]
Hi @aguingand thanks for creating this plugin, nice work :)

**Describe the bug**
I enter multiple empty lines inside the editor. It doesnt translate to empty lines in markdown. Other content renders fine!

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version Versie 107.0.5304.110

**Comment by aguingand** [comment]
Empty paragraphs doesn't exist in markdown but you can enter hard breaks with the [HardBreak](https://tiptap.dev/api/nodes/hard-break) tiptap extension. The shortcut is Cmd+Enter.

**Comment by lennardv2** [comment]
Yes I do use the HardBreak extension. Enters are not showing up in the markdown version, that the problem.

```
<p>a</a>
<p></p>
<p></p>
<p></p>
<br>
<p>b</p>
```

Should become


```
a




b
```

But becomes

```
a
b
```

**Comment by lennardv2** [comment]
Cmd+Enter seems to result in: `` \ ``

```
Some text\
\
\
\
Hmh..
```

**Comment by aguingand** [comment]
This package doesn't save the text "as is" like a textarea. It transforms tiptap nodes / marks to match the CommonMark spec. Your example will render as [two paragraphs](https://spec.commonmark.org/dingus/?text=a%0A%0A%0A%0A%0Ab), and `<br>` are [translated to `\\n`](https://spec.commonmark.org/dingus/?text=Some%20text%5C%0A%5C%0A%5C%0A%5C%0AHmh..).

If you want to use a editor where the text is saved "as is", you should like at editors like [SimpleMDE](https://simplemde.com/)

**Comment by lennardv2** [comment]
Ah yes understood, thanks

**Comment by fridaystreet** [comment]
> Cmd+Enter

did you manage to resolve this, seem to be having this issue?
