### ISSUE TITLE
Missing @tiptap/pm dependency

### ISSUE THREAD

**Issue by abhishiv** [aguingand/tiptap-markdown#80]
**Describe the bug**

Hey @aguingand, thanks for a great package!

Is there a reason why @tiptap/pm is not listed in dependencies while it's referenced in code? This would break a few runtimes which are more stricter than node.

https://cdn.jsdelivr.net/npm/tiptap-markdown@0.8.10/dist/tiptap-markdown.es.js

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aguingand** [comment]
@tiptap/pm is implied be the `@tiptap/core` dependency see https://github.com/ueberdosis/tiptap/blob/develop/packages/core/package.json#L35
